

runtime: nodejs
env: flex

skip_files:
  - ^node_modules$


resources:
  cpu: .2
  memory_gb: .6
  disk_size_gb: 10

manual_scaling:
  instances: 1

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 1
#  cool_down_period_sec: 120
#  cpu_utilization:
#    target_utilization: 0.8  
